### ISSUE TITLE
Register Form

### ISSUE THREAD

**Issue by B-Musick** [B-Musick/synopc#8]
## Description
This form will allow the user to register an account, and submit their information to the database

## Files
templates/register-form.html

## Tasks
- [ ] Registration form
     - [ ] Username
     - [x] First Name
     - [x] Last Name
     - [x] Email address
     - [ ] User ID generated automatically 
- [x] Submit Button
- [ ] Create new User object
- [ ] Submit User object to database
